#!/bin/sh
yaourt -Rdd \
amdgpu-pro \
amdgpu-pro-dkms \
amdgpu-pro-lib32 \
clinfo-amdgpu-pro \
gst-omx-amdgpu-pro \
lib32-amdgpu-pro \
lib32-clinfo-amdgpu-pro \
lib32-gst-omx-amdgpu-pro \
lib32-libdrm2-amdgpu-pro \
lib32-libdrm-amdgpu-pro-amdgpu1 \
lib32-libdrm-amdgpu-pro-dev \
lib32-libdrm-amdgpu-pro-radeon1 \
lib32-libdrm-amdgpu-pro-utils \
lib32-libegl1-amdgpu-pro \
lib32-libgbm1-amdgpu-pro \
lib32-libgbm1-amdgpu-pro-dev \
lib32-libgl1-amdgpu-pro-dri \
lib32-libgl1-amdgpu-pro-ext \
lib32-libgl1-amdgpu-pro-glx \
lib32-libglamor-amdgpu-pro-dev \
lib32-libgles2-amdgpu-pro \
lib32-libopencl1-amdgpu-pro \
lib32-libvdpau-amdgpu-pro \
lib32-mesa-amdgpu-pro-omx-drivers \
lib32-opencl-amdgpu-pro-icd \
lib32-vulkan-amdgpu-pro \
lib32-xserver-xorg-video-amdgpu-pro \
lib32-xserver-xorg-video-glamoregl-amdgpu-pro \
lib32-xserver-xorg-video-modesetting-amdgpu-pro \
libdrm2-amdgpu-pro \
libdrm-amdgpu-pro-amdgpu1 \
libdrm-amdgpu-pro-dev \
libdrm-amdgpu-pro-radeon1 \
libdrm-amdgpu-pro-utils \
libegl1-amdgpu-pro \
libgbm1-amdgpu-pro \
libgbm1-amdgpu-pro-base \
libgbm1-amdgpu-pro-dev \
libgl1-amdgpu-pro-appprofiles \
libgl1-amdgpu-pro-dri \
libgl1-amdgpu-pro-ext \
libgl1-amdgpu-pro-glx \
libglamor-amdgpu-pro-dev \
libgles2-amdgpu-pro \
libopencl1-amdgpu-pro \
libvdpau-amdgpu-pro \
mesa-amdgpu-pro-omx-drivers \
opencl-amdgpu-pro-icd \
vulkan-amdgpu-pro \
xserver-xorg-video-amdgpu-pro \
xserver-xorg-video-glamoregl-amdgpu-pro \
xserver-xorg-video-modesetting-amdgpu-pro \
&& sudo pacman -S xf86-video-amdgpu mesa-libgl lib32-mesa-libgl ocl-icd
